application: enter-app-id-here
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: assets/css

- url: /js
  static_dir: assets/js

- url: /images
  static_dir: assets/images

- url: /_ah/mail/pt@.*app-id\.appspotmail\.com
  script: incoming_email.py

- url: /get-token
  script: main.py

- url: /remove-token
  script: main.py

- url: /save-email
  script: main.py

- url: /remove-email
  script: main.py

- url: /update-schema
  script: main.py
  secure: always
  login: admin

- url: .*
  script: main.py

inbound_services:
- mail

builtins:
- datastore_admin: on
- appstats: on
